routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('posts.index'));
});

Route::resource('posts', 'PostsController', ['only' => [
    'index', 'create', 'store']])->names('posts');

Route::post('posts/search/', 'PostsController@search')->name('posts.search');

app/Models/Posts.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Posts extends Model
{
    protected $fillable = [
        'title',
        'description',
    ];

    public function tags()
    {
        return $this->hasMany(Tags::class, 'post_id', 'id');
    }
}

app/Models/Tags.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Tags extends Model
{
    public $timestamps=false;
    protected $fillable = [
        'name',
        'post_id',
    ];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StorePosts;
use App\Models\Posts;
use App\Models\Tags;
use App\Services\PostServices;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class PostsController extends Controller
{

    private $postServices;

    /**
     * PostsController constructor.
     * @param PostServices $postRepository
     */
    public function __construct(PostServices $postServices)
    {
        $this->postServices = $postServices;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $paginator = $this->postServices->getAllWithPaginate(config('app.perPage'));

        return view('posts.index', compact('paginator'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorePosts $request)
    {
        if ($this->postServices->storePost($request->input())) {
            return redirect()->route('posts.index')->with(['success' => 'Збережено']);
        }
        return back()->withErrors(['msg' => 'Помилка збереження'])
            ->withInput();
    }

    /**
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function search(Request $request)
    {
        $paginator = $this->postServices->getSearchWithPaginate($request->input('search'), config('app.perPage'));
        return view('posts.index', compact('paginator'));
    }
}

resources/views/includes/result_messages.blade.php
@if($errors->any())
    @component('components.result_message',['result' => 'danger'])
        @foreach($errors->all() as $errorTxt)
            <li>{{ $errorTxt}}</li>
        @endforeach
    @endcomponent
@endif

@if(session('success'))
    @component('components.result_message',['result' => 'success'])
        {{ session()->get('success') }}
    @endcomponent
@endif

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog</title>


    <link href="{{asset('css/app.css')}}" rel="stylesheet">

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{{route('posts.index')}}">Головна</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ route('posts.create') }}" }>Додати пост
                        <span class="sr-only">(current)</span>
                    </a>
                </li>

            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
<div class="container">

    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8">
            <main>
                @yield('content')
            </main>
        </div>
        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">
            <form method="POST" action="{{ route('posts.search')}}" enctype="multipart/form-data">
            @csrf
            <!-- Search Widget -->
                <div class="card my-4">
                    <h5 class="card-header">Пошук</h5>
                    <div class="card-body">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search for..." name="search">
                            <span class="input-group-btn">
                <button class="btn btn-secondary" type="submit">Go!</button>
              </span>
                        </div>
                    </div>
                </div>
            </form>


        </div>

    </div>
    <!-- /.row -->

</div>
<!-- /.container -->

<!-- Footer -->
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Blog</p>
    </div>
    <!-- /.container -->
</footer>

<script src="{{asset('js/app.js')}}"></script>

</body>

</html>

resources/views/posts/create.blade.php
@extends('layouts.app')
@section('content')
    @include('includes.result_messages')
    <h1 class="my-4">Створення поста</h1>
    <form method="POST" action="{{ route('posts.store')}}" enctype="multipart/form-data">
        @csrf
        @component('components.inputComponent',['idElement' => 'title','name' =>'Назва поста'])
            <input type="text" class="form-control" id="title" name="title" value="{{ old('title') }}">
        @endcomponent
        @component('components.inputComponent',['idElement' => 'description','name' =>'Опис поста'])
            <textarea class="form-control" id="description" rows="5"
                      name="description">{{ old('description')}}</textarea>
        @endcomponent
        @component('components.inputComponent',['idElement' => 'tags','name' =>'Введіть тег'])
            <div class="input-group mb-3">
                <input type="text" class="form-control" aria-describedby="button-addon2" id="tags"
                       name="tags">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="button-addon2" disabled>+
                    </button>
                </div>
            </div>
        @endcomponent
        @component('components.inputComponent',['idElement' => 'listTags','name' =>'Список тегів'])
            <select multiple class="form-control overflow-hidden" id="listTags" name="listTags[]">
            </select>
        @endcomponent
        <button type="submit" class="btn btn-success">Зберегти</button>
    </form>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')
@section('content')
    @include('includes.result_messages')
    <!-- Blog Post -->
    @foreach($paginator as $item )
    <div class="card mb-4">
        <div class="card-body">
            <h2 class="card-title">{{$item->title}}</h2>
            <p class="card-text">{{$item->description}}</p>
        </div>
        <div class="card-footer text-muted">
            {{$item->created_at}}
            <hr>

            <div class="row wrap">
                <div class="col-lg-12 ">
                    <ol class="mb-0">

                        @foreach($item->tags as $tags )
                        <li>
                            {{$tags->name}}
                        </li>
                        @endforeach
                    </ol>
                </div>
            </div>
        </div>
    </div>
    @endforeach
    <!-- Pagination -->
    @if($paginator->total() > $paginator->count())
        <br>
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        {{ $paginator->links() }}
                    </div>
                </div>
            </div>
        </div>
    @endif
@endsection